name: Activity_Rewards
version: ${project.version}
main: me.ofearr.activity_rewards.Activity_Rewards
api-version: 1.16
authors: [oFearr]
commands:
  reloadrewards:
    aliases: [rewardsreload, rr, activityrewards-reload, rewards-reload]
    description: Reload the rewards from config.
